-- Seed for strategy_family_param. Re-run on every open of strategies.db, so editing a row here is the way to change it.
INSERT OR REPLACE INTO strategy_family_param (family, param, kind, role, gridsearchable, grid_values, why_not) VALUES
('streak', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('streak', 'name', 'text', 'label', 0, NULL, 'a label'),
('streak', 'signal_symbol', 'symbol', 'entry', 0, NULL, 'the watch symbol defines the strategy. A different watch symbol is a different row'),
('streak', 'trade_symbol', 'symbol', 'symbol', 1, '[]', 'the trade symbols come from the -symbols or -symbols-from flag, not from this table'),
('streak', 'direction', 'text', 'entry', 0, NULL, 'drop and rally are different rules, so they are separate rows'),
('streak', 'signal_days', 'int', 'entry', 1, '[1,2,3,4,5]', NULL),
('streak', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', NULL),
('streak', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', NULL),
('streak', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', NULL),
('streak', 'regime', 'text', 'entry', 1, '["All Regimes","{signal_symbol}>=SMA200","{signal_symbol}<SMA200"]', NULL),
('streak', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('streak', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('streak', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('streak', 'next_day_limit', 'int', 'entry', 0, NULL, 'an execution switch, not searched'),
('streak', 'source_strategy', 'text', 'label', 0, NULL, 'provenance of a promoted row'),
('streak', 'source_label', 'text', 'label', 0, NULL, 'provenance of a promoted row'),
('streak', 'win_rate', 'real', 'stat', 0, NULL, 'a result written by promote, not an input'),
('streak', 'total_trades', 'int', 'stat', 0, NULL, 'a result written by promote, not an input'),
('tree', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('tree', 'name', 'text', 'label', 0, NULL, 'a label'),
('tree', 'signal_symbol', 'symbol', 'entry', 0, NULL, 'the watch symbol defines the strategy'),
('tree', 'trade_symbol', 'symbol', 'symbol', 0, NULL, 'the traded symbol defines the strategy'),
('tree', 'direction', 'text', 'entry', 0, NULL, 'a label of the row, the entries come from the saved tree'),
('tree', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', NULL),
('tree', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', NULL),
('tree', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', NULL),
('tree', 'coil_range_max', 'real', 'legacy', 0, NULL, 'unused: entries come from the decision tree saved by train tree, not from this threshold'),
('tree', 'sma_bounce_min', 'real', 'legacy', 0, NULL, 'unused: entries come from the decision tree saved by train tree, not from this threshold'),
('tree', 'sma_bounce_max', 'real', 'legacy', 0, NULL, 'unused: entries come from the decision tree saved by train tree, not from this threshold'),
('tree', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('tree', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('tree', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('tree', 'next_day_limit', 'int', 'entry', 0, NULL, 'an execution switch, not searched'),
('tree', 'source_strategy', 'text', 'label', 0, NULL, 'provenance of the row'),
('tree', 'source_label', 'text', 'label', 0, NULL, 'provenance of the row'),
('tree', 'win_rate', 'real', 'stat', 0, NULL, 'a result, not an input'),
('tree', 'total_trades', 'int', 'stat', 0, NULL, 'a result, not an input'),
('markov', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('markov', 'name', 'text', 'label', 0, NULL, 'a label'),
('markov', 'signal_symbol', 'symbol', 'entry', 0, NULL, 'the model is trained per signal symbol. A different symbol is a different row'),
('markov', 'trade_symbol', 'symbol', 'symbol', 0, NULL, 'the traded symbol defines the strategy'),
('markov', 'direction', 'text', 'entry', 0, NULL, 'part of the rule'),
('markov', 'target_state', 'text', 'entry', 0, NULL, 'bull, bear and sideways are different entry sets and gridsearch has no markov entries stage yet. Entries are taken from the saved model for the row state'),
('markov', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', NULL),
('markov', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', NULL),
('markov', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', NULL),
('markov', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('markov', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('markov', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('markov', 'next_day_limit', 'int', 'entry', 0, NULL, 'an execution switch, not searched'),
('markov', 'source_strategy', 'text', 'label', 0, NULL, 'provenance of the row'),
('markov', 'source_label', 'text', 'label', 0, NULL, 'provenance of the row'),
('markov', 'win_rate', 'real', 'stat', 0, NULL, 'a result, not an input'),
('markov', 'total_trades', 'int', 'stat', 0, NULL, 'a result, not an input'),
('hold', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('hold', 'name', 'text', 'label', 0, NULL, 'a label'),
('hold', 'symbol', 'symbol', 'symbol', 0, NULL, 'the held symbol defines the strategy'),
('hold', 'total_return', 'int', 'entry', 0, NULL, 'a switch between price and dividend-adjusted prices, not searched'),
('hold', 'allocation_pct', 'real', 'sizing', 0, NULL, 'buy and hold has no entry or exit parameter to search'),
('hold', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('hold', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('hold_bail', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('hold_bail', 'name', 'text', 'label', 0, NULL, 'a label'),
('hold_bail', 'symbol', 'symbol', 'symbol', 0, NULL, 'the held symbol defines the strategy'),
('hold_bail', 'trailing_stop_pct', 'real', 'exit', 0, NULL, 'gridsearch has no hold_bail signal stage, so it cannot evaluate a changed trailing stop yet'),
('hold_bail', 'sma_reentry_period', 'int', 'entry', 0, NULL, 'gridsearch has no hold_bail signal stage, so it cannot evaluate a changed re-entry period yet'),
('hold_bail', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('hold_bail', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('hold_bail', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter');
