-- Seed for strategy_family_param. Re-run on every open of strategies.db, so editing a row here is the way to change it.
INSERT OR REPLACE INTO strategy_family_param (family, param, kind, role, gridsearchable, grid_values, why_not) VALUES
('streak', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('streak', 'name', 'text', 'label', 0, NULL, 'a label'),
('streak', 'signal_symbol', 'symbol', 'entry', 0, NULL, 'the watch symbol defines the strategy. A different watch symbol is a different row'),
('streak', 'trade_symbol', 'symbol', 'symbol', 1, '[]', 'the trade symbols come from the -symbols or -symbols-from flag, not from this table'),
('streak', 'direction', 'text', 'entry', 0, NULL, 'drop and rally are different rules, so they are separate rows'),
('streak', 'signal_days', 'int', 'entry', 1, '[1,2,3,4,5]', NULL),
('streak', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', NULL),
('streak', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', NULL),
('streak', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', NULL),
('streak', 'regime', 'text', 'entry', 1, '["All Regimes","{signal_symbol}>=SMA200","{signal_symbol}<SMA200"]', NULL),
('streak', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('streak', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('streak', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('streak', 'next_day_limit', 'int', 'legacy', 0, NULL, 'unused: every streak row buys at the next session open (StrategyConfig.NextDayOpenEntry), whatever this says'),
('streak', 'source_strategy', 'text', 'label', 0, NULL, 'provenance of a promoted row'),
('streak', 'source_label', 'text', 'label', 0, NULL, 'provenance of a promoted row'),
('streak', 'win_rate', 'real', 'stat', 0, NULL, 'a result written by promote, not an input'),
('streak', 'total_trades', 'int', 'stat', 0, NULL, 'a result written by promote, not an input'),
('tree', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('tree', 'name', 'text', 'label', 0, NULL, 'a label'),
('tree', 'signal_symbol', 'symbol', 'entry', 0, NULL, 'the watch symbol defines the strategy'),
('tree', 'trade_symbol', 'symbol', 'symbol', 0, NULL, 'the traded symbol defines the strategy'),
('tree', 'direction', 'text', 'entry', 0, NULL, 'a label of the row, the entries come from the saved tree'),
('tree', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', NULL),
('tree', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', NULL),
('tree', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', NULL),
('tree', 'coil_range_max', 'real', 'legacy', 0, NULL, 'unused: entries come from the decision tree saved by train tree, not from this threshold'),
('tree', 'sma_bounce_min', 'real', 'legacy', 0, NULL, 'unused: entries come from the decision tree saved by train tree, not from this threshold'),
('tree', 'sma_bounce_max', 'real', 'legacy', 0, NULL, 'unused: entries come from the decision tree saved by train tree, not from this threshold'),
('tree', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('tree', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('tree', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('tree', 'next_day_limit', 'int', 'entry', 0, NULL, 'an execution switch, not searched'),
('tree', 'source_strategy', 'text', 'label', 0, NULL, 'provenance of the row'),
('tree', 'source_label', 'text', 'label', 0, NULL, 'provenance of the row'),
('tree', 'win_rate', 'real', 'stat', 0, NULL, 'a result, not an input'),
('tree', 'total_trades', 'int', 'stat', 0, NULL, 'a result, not an input'),
('markov', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('markov', 'name', 'text', 'label', 0, NULL, 'a label'),
('markov', 'signal_symbol', 'symbol', 'entry', 0, NULL, 'the model is trained per signal symbol. A different symbol is a different row'),
('markov', 'trade_symbol', 'symbol', 'symbol', 0, NULL, 'the traded symbol defines the strategy'),
('markov', 'direction', 'text', 'entry', 0, NULL, 'part of the rule'),
('markov', 'target_state', 'text', 'entry', 0, NULL, 'bull, bear and sideways are different entry sets and gridsearch has no markov entries stage yet. Entries are taken from the saved model for the row state'),
('markov', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', NULL),
('markov', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', NULL),
('markov', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', NULL),
('markov', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('markov', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('markov', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('markov', 'next_day_limit', 'int', 'entry', 0, NULL, 'an execution switch, not searched'),
('markov', 'source_strategy', 'text', 'label', 0, NULL, 'provenance of the row'),
('markov', 'source_label', 'text', 'label', 0, NULL, 'provenance of the row'),
('markov', 'win_rate', 'real', 'stat', 0, NULL, 'a result, not an input'),
('markov', 'total_trades', 'int', 'stat', 0, NULL, 'a result, not an input'),
('hold', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('hold', 'name', 'text', 'label', 0, NULL, 'a label'),
('hold', 'symbol', 'symbol', 'symbol', 0, NULL, 'the held symbol defines the strategy'),
('hold', 'total_return', 'int', 'entry', 0, NULL, 'a switch between price and dividend-adjusted prices, not searched'),
('hold', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('hold', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('hold', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('hold', 'trailing_stop_pct', 'real', 'exit', 0, NULL, 'gridsearch has no hold signal stage for a changed trailing stop yet. 0 never bails'),
('hold', 'sma_reentry_period', 'int', 'entry', 0, NULL, 'gridsearch has no hold signal stage for a changed re-entry period yet. 0 never re-enters'),
('hold', 'hold_days', 'int', 'exit', 1, '[2,4,6,8,10,12,15]', 'a regime row sets its own hold per entry, so it is not searched. 0 or 99999 is no limit'),
('hold', 'take_profit_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.10]', '0 is no take-profit'),
('hold', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', '0 is no stop'),
('hold', 'regime_symbol', 'symbol', 'entry', 0, NULL, 'gridsearch has no hold signal stage for a changed regime yet. Empty holds without a regime'),
('rotation', 'id', 'text', 'identity', 0, NULL, 'the row key'),
('rotation', 'name', 'text', 'label', 0, NULL, 'a label'),
('rotation', 'symbols', 'text', 'symbol', 0, NULL, 'the candidate list defines the strategy. Empty means every symbol in the market database'),
('rotation', 'universe_size', 'int', 'entry', 0, NULL, 'gridsearch has no rotation signal stage yet. A search needs the whole ranking rerun per value'),
('rotation', 'top_k', 'int', 'entry', 0, NULL, 'gridsearch has no rotation signal stage yet. A search needs the whole ranking rerun per value'),
('rotation', 'exit_buffer', 'int', 'exit', 0, NULL, 'gridsearch has no rotation signal stage yet. A search needs the whole ranking rerun per value'),
('rotation', 'max_weight_pct', 'real', 'sizing', 0, NULL, 'a cap on one name, applied with allocation_pct / top_k'),
('rotation', 'regime_symbol', 'symbol', 'entry', 0, NULL, 'the gate symbol defines the strategy'),
('rotation', 'regime_sma', 'int', 'entry', 0, NULL, 'gridsearch has no rotation signal stage yet. 0 turns the gate off'),
('rotation', 'allocation_pct', 'real', 'sizing', 0, NULL, 'sizing, set by the -alloc flag for the whole run'),
('rotation', 'cash_yield', 'real', 'cost', 0, NULL, 'an account setting, not a strategy parameter'),
('rotation', 'slippage_pct', 'real', 'cost', 0, NULL, 'a cost assumption, not a strategy parameter'),
('rotation', 'period', 'text', 'entry', 1, '["1d","1w","1m","1q","1y"]', NULL),
('rotation', 'side', 'text', 'entry', 0, NULL, 'long, short and inverse are different trades, so they are separate rows'),
('rotation', 'pick', 'text', 'entry', 0, NULL, 'winner and loser are opposite rules, so they are separate rows'),
('rotation', 'entry_limit_pct', 'real', 'entry', 1, '[1.0,0.97,0.95,0.9]', 'a long period row only. 1.0 buys at the previous close, 0.9 at 10% under it'),
('rotation', 'take_profit_pct', 'real', 'exit', 1, '[0.03,0.04,0.05,0.06,0.07,0.08]', 'a long period row only'),
('rotation', 'hold_days', 'int', 'exit', 1, '[1,2,3,4,5]', 'a long period row only. Sessions held after the entry session, 0 holds to the period end'),
('rotation', 'stop_loss_pct', 'real', 'exit', 1, '[0,0.02,0.03,0.05,0.07]', 'a long period row only. 0 is no stop');
