-- 04_annual_cagr_audit.sql
-- Year-by-Year Performance, Period Return, and Metrics Audit for GLD Decline Strategy
-- Compatible with standard SQLite3 (no external math extensions required).
--
-- Prerequisites:
--   ATTACH DATABASE 'data/market_history.db' AS market;
--   Primary DB contains 'equity_curve' and 'trades' tables generated by backtest.

WITH yearly_ranges AS (
    SELECT 
        strftime('%Y', date) AS year,
        MIN(date) AS first_date,
        MAX(date) AS last_date,
        COUNT(*) AS trading_days
    FROM equity_curve
    GROUP BY strftime('%Y', date)
),
prior_year_links AS (
    SELECT 
        year,
        first_date,
        last_date,
        trading_days,
        LAG(last_date) OVER (ORDER BY year) AS prior_last_date
    FROM yearly_ranges
),
equity_points AS (
    SELECT 
        p.year,
        COALESCE(p.prior_last_date, p.first_date) AS start_date,
        p.last_date AS end_date,
        p.trading_days,
        COALESCE(e_start.total_equity, 100000.0) AS start_equity,
        e_end.total_equity AS end_equity,
        julianday(p.last_date) - julianday(COALESCE(p.prior_last_date, p.first_date)) AS calendar_days
    FROM prior_year_links p
    LEFT JOIN equity_curve e_start ON e_start.date = p.prior_last_date
    JOIN equity_curve e_end ON e_end.date = p.last_date
),
year_stats AS (
    SELECT 
        strftime('%Y', date) AS year,
        MAX(drawdown_pct) * 100.0 AS max_dd_pct,
        AVG(cash / total_equity) * 100.0 AS avg_idle_cash_pct
    FROM equity_curve
    GROUP BY strftime('%Y', date)
),
gld_prices AS (
    SELECT substr(date, 1, 10) AS date, close FROM market.backtest_start WHERE symbol = 'GLD'
),
voo_prices AS (
    SELECT substr(date, 1, 10) AS date, close FROM market.backtest_start WHERE symbol = 'VOO'
),
trade_stats AS (
    SELECT 
        strftime('%Y', exit_date) AS year,
        COUNT(*) AS total_trades,
        SUM(CASE WHEN net_pnl > 0 THEN 1 ELSE 0 END) AS wins,
        SUM(CASE WHEN net_pnl <= 0 THEN 1 ELSE 0 END) AS losses
    FROM trades
    GROUP BY strftime('%Y', exit_date)
)
SELECT 
    ep.year,
    ep.start_date || ' to ' || ep.end_date AS time_window,
    ep.trading_days,
    ROUND(ep.calendar_days, 1) AS calendar_days,
    ROUND(ep.start_equity, 2) AS start_equity,
    ROUND(ep.end_equity, 2) AS end_equity,
    ROUND(ep.end_equity - ep.start_equity, 2) AS net_profit,
    ROUND(((ep.end_equity - ep.start_equity) / ep.start_equity) * 100.0, 2) AS period_return_pct,
    ROUND(ys.max_dd_pct, 2) AS max_drawdown_pct,
    ROUND(ys.avg_idle_cash_pct, 1) AS avg_idle_cash_pct,
    ROUND(COALESCE(g_start.close, (SELECT close FROM gld_prices WHERE date >= ep.start_date ORDER BY date ASC LIMIT 1)), 2) AS gld_start,
    ROUND(COALESCE(g_end.close, (SELECT close FROM gld_prices WHERE date <= ep.end_date ORDER BY date DESC LIMIT 1)), 2) AS gld_end,
    ROUND(((COALESCE(g_end.close, (SELECT close FROM gld_prices WHERE date <= ep.end_date ORDER BY date DESC LIMIT 1)) -
            COALESCE(g_start.close, (SELECT close FROM gld_prices WHERE date >= ep.start_date ORDER BY date ASC LIMIT 1))) /
            COALESCE(g_start.close, (SELECT close FROM gld_prices WHERE date >= ep.start_date ORDER BY date ASC LIMIT 1))) * 100.0, 2) AS gld_return_pct,
    ROUND(COALESCE(v_start.close, (SELECT close FROM voo_prices WHERE date >= ep.start_date ORDER BY date ASC LIMIT 1)), 2) AS voo_start,
    ROUND(COALESCE(v_end.close, (SELECT close FROM voo_prices WHERE date <= ep.end_date ORDER BY date DESC LIMIT 1)), 2) AS voo_end,
    ROUND(((COALESCE(v_end.close, (SELECT close FROM voo_prices WHERE date <= ep.end_date ORDER BY date DESC LIMIT 1)) -
            COALESCE(v_start.close, (SELECT close FROM voo_prices WHERE date >= ep.start_date ORDER BY date ASC LIMIT 1))) /
            COALESCE(v_start.close, (SELECT close FROM voo_prices WHERE date >= ep.start_date ORDER BY date ASC LIMIT 1))) * 100.0, 2) AS voo_return_pct,
    COALESCE(ts.total_trades, 0) AS trades,
    COALESCE(ts.wins, 0) AS wins,
    COALESCE(ts.losses, 0) AS losses,
    ROUND(COALESCE(ts.wins * 100.0 / NULLIF(ts.total_trades, 0), 0.0), 1) AS win_rate_pct
FROM equity_points ep
JOIN year_stats ys ON ep.year = ys.year
LEFT JOIN gld_prices g_start ON g_start.date = ep.start_date
LEFT JOIN gld_prices g_end ON g_end.date = ep.end_date
LEFT JOIN voo_prices v_start ON v_start.date = ep.start_date
LEFT JOIN voo_prices v_end ON v_end.date = ep.end_date
LEFT JOIN trade_stats ts ON ep.year = ts.year
ORDER BY ep.year ASC;
